### ISSUE TITLE
fireFoam "smallPoolFire3D" Tutorial

### ISSUE THREAD

**Issue by MyilsamyDinesh** [blueCFD/Core#106]
Hi everyone  I am a beginner to OpenFoam. Currently, I am practising OpenFOAM on Windows computer using blueCFD-Core2017.  
I am specifically interested in fireFoam section. In the fireFoam section, I am practising a tutorial entitled as "smallPoolFire3D". Although I could simulate the tutorial I couldn't understand one thing in  "blockMeshDict" input file. In that input file why the "inlet boundary" vertices have not mentioned? while the outlet, base and side vertices have specified. 
Suppose if I want to change the inlet boundary face, what are the other input files that I have to consider?
I kindly request for your guidance to learn OpenFoam.

**Comment by wyldckat** [comment]
Thanks for the indirect reminder that I had completely forgotten to provide a link to the official OpenFOAM Foundation User Guides: https://cfd.direct/openfoam/user-guide/

I've updated our page http://bluecfd.github.io/Core/UserGuide/ accordingly.

----

As for your question, I strongly suggest that you study chapters 2 and 5, in order to find the answers you are looking for.

Beyond this, if you have additional questions on how to use OpenFOAM, you can either:

* Contact us for paid support, as explained here: http://joomla.bluecape.com.pt/index.php?option=com_content&task=view&id=18&Itemid=30#How%20to%20Get%20It

* For free support, please use the OpenFOAM community forums, such as the one at CFD-Online: https://www.cfd-online.com/Forums/openfoam/


Please only use this Issue Tracker we are on, if there is a clear problem with using blueCFD-Core.
