### ISSUE TITLE
swak4Foam problem at compiling

### ISSUE THREAD

**Issue by AlexLadino** [blueCFD/Core#112]
problem with blueCFDcore2016 OF 4.x 
windows 10 /intel  i7-770HQ 
[log.make.gz](https://github.com/blueCFD/Core/files/2457047/log.make.gz)

**Comment by wyldckat** [comment]
The error message indicates that the path `C:\Program Files` was the breaking point, due to the space in the name.

Perhaps you are using blueCFD-Core 2016-1 and not 2016-2?

Either way, these steps should help solve the issue:

1. Please follow the instructions given here: https://github.com/blueCFD/Core/wiki/Quick-notes-on-how-to-update-build#setting-up-the-work-environment

2. Then you can retry building swak4Foam by running the following commands in the new terminal:

    ```
    user
    cd swak4Foam
    wclean all
    ```

    * Then continue from step 6 on the installation instructions: https://github.com/blueCFD/Core/wiki/Building-swak4Foam-with-blueCFD-Core

Please let us know here if this solves the issue or not.

**Comment by AlexLadino** [comment]
Thank you for your attention. 
In fact, i just uninstalled the 2016-1 version and installed the 2006-2 in a root folder (i.e C:\blueCFD). swak4Foam compiled succesfully.
