### ISSUE TITLE
error using wmake for compiling new solver

### ISSUE THREAD

**Issue by Flopi76** [blueCFD/Core#121]
Hello, 
I'm new to OpenFoam and blueCFD and I have a problem with compiling a new solver. Even without doing any changes, when I copy and paste the new solver in another folder with another name and when I try to compile it, I have the following error:

make: ***  Aucune règle pour fabriquer la cible « Make/mingw_w64GccDPInt32Opt/serpentinization_1.C.dep », nécessaire pour « Make/mingw_w64GccDPInt32Opt/serpentinization_1.o ». Arrêt.

which translated to english should read: no rule to make target ---- necessary for ------ stop

Any idea of why I get this error ?
Thanks,

**Comment by wyldckat** [comment]
Quick question: Did you first follow the instructions given here: https://github.com/blueCFD/Core/wiki/Quick-notes-on-how-to-update-build#work-environment-for-bluecfd-core-2016-2-and-2017

It's not straight forward to get there, but the entry point of the search is the Frequently Asked Questions page: http://bluecfd.github.io/Core/FAQ/


The reason why I ask this and point this out, is because the information you've provided does not indicate the full path of the folder where you are working in. And if that path has spaces in it, it could possibly explain the error you have gotten.

Either that or the path is already very long. If you run this command inside the folder where you are working with the custom solver:

```
pwd | wc -c
```

what is the number it gives you? It should give the number of characters in the full path where you are working and if it's larger than 260, that is the reason for the problem and the instructions mentioned in my first paragraph direct you to how to solve that issue.

**Comment by Flopi76** [comment]
Hi, 
Thanks for the quick answer. The number I get after the command you gave is 62.
I actually had not done the work environment change from  the llink you gave me, but sadly it did not improve the result. Even after setting the substitute Drive, I still have the same error.

**Comment by wyldckat** [comment]
OK, please run the following commands within the source code folder you are working in:

```
pwd
find
cat Make/files
```

This will tell us:
1. The path you are working on, to make sure that there are no problematic characters in the path.
2. The files that exist in that folder.
3. The content of the file "Make/files".

My suspicion is that the file name "serpentinization_1.C" is actually named "serpentinization_1.c" (lower case 'C'), but it's just a wild guess.

**Comment by Flopi76** [comment]
Pretty good guess indeed. I used lower case... I renamed the file with .C and tried compiling. It goes through much of the process but tells me this at the end:

 X:/ofuser-of5/platforms/mingw_w64GccDPInt32Opt/bin/serpentinization_1.pdb: cannot load PDB helper DLL
Error occurred with cv2pdb, have stripped binary as a workaround.

However, since it seems to work on my case, I guess this is not a big issue?
Thanks a lot for your help !

**Comment by wyldckat** [comment]
That error message is not a problem, it's just letting you know that it was not able to generate additional debug information. Everything should work as intended, it's just that when it crashes, it will not tell you where exactly it crashed in your custom code.
