### ISSUE TITLE
Is checkmesh -writeAllFields code being considered for implementation here?

### ISSUE THREAD

**Issue by DaleKramer** [blueCFD/Core#140]
Checkmesh -writeAllFields has been implemented at on OF.com code since v1706.

That is a very useful parameter, will it be implemented on OF.org and included in a blueCFD release soon?

**Comment by wyldckat** [comment]
I have no idea if it will be implemented at OpenFOAM.org, you will have to ask/suggest that to them at https://bugs.openfoam.org - but if you do suggest, please provide more details about what you are suggesting, do not simply state "can you do the same that OpenFOAM.com did", because the answer will possibly be something like "they could have provided it to us themselves and haven't yet"...

Either way, we are still focusing in improving our workflow for the future releases of blueCFD-Core, therefore we don't have any scheduled plans yet for integrating the developments from OpenFOAM.com. That said, OpenFOAM.com is developing their own port of their OpenFOAM development line for running directly on Windows.
