### ISSUE TITLE
Courant number diverges

### ISSUE THREAD

**Issue by ananddoss2004** [blueCFD/Core#154]
Suddenly the results residuals get diverged despite having proper mesh. Can anyone explain?
[log.zip](https://github.com/blueCFD/Core/files/5161417/log.zip)

**Comment by wyldckat** [comment]
Quick answer:

1. General OpenFOAM usage questions should either be asked at the public forums in CFD Online: https://www.cfd-online.com/Forums/openfoam/ - or a support contract can be provided by us as well at bluecape.com.pt: https://joomla.bluecape.com.pt/index.php?option=com_content&task=view&id=18&Itemid=30#Statement%20of%20Service - see "For those who purchase the hourly support packages".

2. Looking at the log file, it seems like the problem was that you haven't properly read the very first tutorial in the OpenFOAM User Guide, which is also provided in blueCFD-Core, given that it's in OpenFOAM's own folders as well.

**Comment by wyldckat** [comment]
PS: Sorry, forgot to mention that `icoFoam` should not be used for Courant numbers higher than 0.5.

**Comment by ananddoss2004** [comment]
Issue resolved. Thanks once again. Next time i make sure i will come up with big issue 😉
