### ISSUE TITLE
Installation swak4Foam bluecfdcore 2017-2 windows10

### ISSUE THREAD

**Issue by torodecamargue** [blueCFD/Core#182]
Hello,

I have not the correct output message after installing following the procedure.
Can you please help me?

[log.make.gz](https://github.com/blueCFD/Core/files/6986142/log.make.gz)

**Comment by wyldckat** [comment]
Greetings @torodecamargue,

My apologies for taking so long to get back to you on this, but when you reported this issue, I was on vacation and since I got from vacation, I had to take care of a ton of work...

I don't know if you are still having this issue, but from the error message you've gotten, I got the feeling that you haven't followed the instructions given here: https://github.com/blueCFD/Core/wiki/Building-swak4Foam-with-blueCFD-Core#building-with-bluecfd-core-2017

Then again, it also looks like you did follow the instructions... did you also follow the following sub-step mentioned at step number 7? Namely this:
> * Optional: If you using more than one core are running it again, to overcome some multi-core racing conditions:
>
> ```
> ./Allwmake > log.make 2>&1
> ```


Best regards,
Bruno
