### ISSUE TITLE
Setup - blueCFD-Cro Installation never getting completed

### ISSUE THREAD

**Issue by dasundee** [blueCFD/Core#262]
To whom it may concern,
I do have 11th Generation Intel Core i7 2.80 GHZ with 32GB of RAM and 64-bit system with Windows 11 Pro. I am trying to install blueCFD Core many times but the installation isn't getting comp
![Keep on installing 28-10-2024](https://github.com/user-attachments/assets/3b7b75de-3351-4820-b1fa-1014e4ca39cd)
![System Properties 28-10-2024](https://github.com/user-attachments/assets/76fb1dd2-3720-41b9-8226-73ea4033e778)
leted at every time and its keep on installing.

**Comment by wyldckat** [comment]
Greetings @dasundee,

A few questions:

1. What is the installation path where you are trying to install blueCFD-Core?
    * I ask this because this can happen when trying to install on a network-based location.

2. Are you installing with or without administrative permissions?

Best regards,
Bruno

**Comment by dasundee** [comment]
Hi Bruno,
I am trying to install this just in my local C drive and yes with Administrator rights. 
But its just keep installing for days until I stop it.

**Comment by wyldckat** [comment]
I do need to know the complete installation path where you are trying to install blueCFD-Core, because the problem might depend on the path itself.

Is it:
1. `C:\blueCFD-Core\2024\`
2. `C:\Program Files\blueCFD-Core-2024`
3. Another path name.

**Comment by dasundee** [comment]
Hi Bruno,
My installation path is C:\Program Files\blueCFD-Crore-2017
(Finally I tried installing 2017 and earlier it was 2024, but the result is same).

**Comment by wyldckat** [comment]
Hi @dasundee,

Regarding version 2014, there is a bug in blueCFD-Core 2024-1 which does not allow running things properly from the default installation path, which is why everywhere we were able to announce near the download link, we indicate that a path without spaces must be used, hence the example: `C:\blueCFD-Core\2024\`

As for the issue you are seeing, one way to try and figure out where the installer stalls and doesn't go forward, is to use Windows' `Resource Monitor` application, then go to the tab `Disk` and select both blueCFD-Core's installer and `System` entries on the top part, as shown in the image below:

![Screenshot 2024-10-28 124601](https://github.com/user-attachments/assets/ca916ecb-7532-4d0a-91bd-95d7600e7c7c)

Then it should list on the second part below the files being written to, for these two applications. Make sure to sort the column `Total (B/sec)`, so that it's possible to see the last files the installer has tried to write to.
The reason why the `System` entry is needed is because the installer hands over the files being unpacked to the Windows system, for writing to the disk, at least from what it looks like.

From what I can figure out, around the location of the progress bar that you shared, is when the installer is deploying the GCC compiler. In the image I show above, there are 4 files that are apparently still being worked on, as part of the GCC compiler, even a while after the installer has deployed them. So my guess is that the anti-virus (Windows Defender in my case) is still working on them, trying to figure out if they are good files or bad files.

With luck, this is enough to figure out which files the installer gets stuck with.
If not, we will have to create a new installer that visually shows which file is being installed at each moment, so that it is easier to diagnose why it's stopping there in your system.

My guesses at the moment are:
1. The main issue might have to do with the Anti-virus stopping the installer, while it investigates the files being installed.
2. The possibility is that Windows set the CPU to efficiency power mode, which makes the anti-virus take a lot longer to analyse files. Setting it to Performance mode might help speed things along.

blueCFD-Core 2024-1 installs over 110000 files, as shown below:
![image](https://github.com/user-attachments/assets/1c87b340-9bff-43cf-9305-b076024bdd2d)

So seeing the properties of the target folder as shown above, when it stalls, is another possible way to diagnose where the installer stops progressing.

Best regards,
Bruno

**Comment by dasundee** [comment]
Hi Bruno,
It worked.
I have turned off my Kaspersky Antivirus, Defender Antivirus and Seqrite Antivirus and changed the Power Mode to Best Performance and it took few hours but got successfully installed.
Thanks!

**Comment by wyldckat** [comment]
Hi @dasundee,

I hope you disconnected the machine from the Internet during that time that you had all 3 anti-virus turned off.

If you need to install any other versions of blueCFD-Core, I advise you to:
1. Test the installer directly with each individual anti-virus.
2. Turn off Internet access, before turning off the anti-viruses.
3. Only turn off one anti-virus at a time, when the installer seems to stop working, to try and see which one is locking up permissions. Keep at least one of them turned on, just in case.
4. Usually there is also the possibility to add a permission for the folder or installer for the anti-virus to not be as forceful.
5. Turn back on all anti-virus after installation and only then turn back on the Internet access.
6. Re-check with each anti-virus the blueCFD-Core installation... just in case.

And many thanks for the feedback!
Best regards,
Bruno
