### ISSUE TITLE
Options for silent installation of blueCFD-core on classroom PC's

### ISSUE THREAD

**Issue by caddison2016** [blueCFD/Core#33]
Could someone please point me to the options on the blueCFD-core Windows installer for a silent installation (i.e no interaction). Alternatively, could someone point to where the silent installer might reside and can be downloaded?

This is necessary so we can pre-install the BlueCFD installation of OpenFOAM and friends on classroom PC's for a course in January.

Thanks

**Comment by wyldckat** [comment]
I've started working on this soon after your report, but didn't manage to finish it yet. The instructions written so far are available here: https://github.com/blueCFD/Core/wiki/Command-line-installation-options-for-blueCFD-Core-installers

I'm aiming towards having these instructions written by the end of today.

Furthermore, I'm not certain of a date yet, but my objective is to release blueCFD-Core 2016-2 in the next couple of weeks.

**Comment by caddison2016** [comment]
That is brilliant. Thanks very much. Our Windows team have managed what appears to be a working bodge on the installation – so install things and take a snapshot and then build an install package from there and that seems to work, so would be delighted to test any silent installation you might have – just makes things a lot more reassuring for our January course.

Cliff

--

Cliff Addison
Manager
Advanced Research Computing
Computing Services Department
Brownlow Hill Building
University of Liverpool
Liverpool L69 3GG
UK

Phone: +44 151 794 3753
FAX:   +44 151 794 4442

**Comment by wyldckat** [comment]
Yes, a snapshot of the folder will do the trick, because the majority of the installation is self-contained. 

But be careful with 2 very important details that the installer does by default:
 1. The default installation folder is in the Windows' default `Program Files` folder.
 2. The default options will change the permissions to full write permissions on several folders within the `blueCFD-Core-2016-1` folder.

The last one is because the environment is replicating one of the common installation structures for OpenFOAM on Linux, where the user has full read-write control over the folders where OpenFOAM is installed.

This to say that it really depends on your security protocols for installing software on those machines. If you don't want users messing with the contents of the files and folders in `C:\Program Files`, then please install blueCFD-Core in a folder where users can make changes, for example: `C:\blueCFD-Core-2016-1`

I'll provide more details about this on the wiki page as soon as I can.


By the way, I've edited the comment you've sent via email and removed sensitive contact information that came with it (essentially the signature information and email address). Please be careful when answering emails to Github issue trackers, because it will post all of the textual content of the email received.

**Comment by caddison2016** [comment]
Our system is a bit strange – since BlueCFD will be installed on teaching centre machines for several weeks, we don’t want students writing into any potentially shared area – each student has his / her own storage that is tied to their roaming profile – not a good place for installations. Different students will run on different machines over the course.

Therefore, we’ll be getting students to copy over the Tutorial folder into their own storage and running OpenFOAM from there plus with the course assignments.

I’ll check with our Windows people whether the change in permissions is honoured or not. I suspect it might not be.

Thanks for pointing this out.

Cliff

P.S. Also thanks for fixing up my submission, I was trying to follow conventions, but clearly I stuck too much of my information in there.

--

Cliff Addison
Manager
Advanced Research Computing
Computing Services Department
Brownlow Hill Building
University of Liverpool
Liverpool L69 3GG
UK

Phone: +44 151 794 3753
FAX:   +44 151 794 4442

**Comment by caddison2016** [comment]
Actually, I looked at where the INNO installation materials modified permissions, and I replicated that -- more or less. I can't actually open up all the permissions because one of the subtrees is the one that contains paths that are too long. The applying of permissions dies when it reaches those. Therefore everything after that point doesn't get its permissions changed.

Thanks,
Lisa.

**Comment by wyldckat** [comment]
The wiki page is now written and mostly tested: https://github.com/blueCFD/Core/wiki/Command-line-installation-options-for-blueCFD-Core-installers

I believe I didn't forget to document anything regarding the possible options. If you have any questions, feel free to ask! And suggestions are also welcome!

Beyond this, I've already created the issue #34, to improve these kinds of installations. Hopefully it will ready with blueCFD-Core 2016-2.

**Comment by wyldckat** [comment]
@caddison2016: I'm closing this issue for now. Feel free to re-open if you have problems!

**Comment by wyldckat** [comment]
@caddison2016: Just to let you know that as of blueCFD-Core 2016-2, we support the ability to have a read-only installation of blueCFD-Core.

 * Download page: http://bluecfd.github.io/Core/Downloads/
 * Information about the read-only installation: http://bluecfd.github.io/Core/FAQ/bluecfd-core-read-only-installation/
 * The wiki page has been updated as well: https://github.com/blueCFD/Core/wiki/Command-line-installation-options-for-blueCFD-Core-installers
