### ISSUE TITLE
 OpenFOAM-4.x ~/ejemplos/cavity/cavity/system

### ISSUE THREAD

**Issue by HugoSiles** [blueCFD/Core#39]
I am all new to OpenFOAM. I have installed it on windows using blueCFD-Core-2016\OpenFOAM-4.x.
When running in the case cavity the excutable blockMesh.exe, I get the following error:

 FOAM FATAL IO ERROR:
cannot find file

file: C:/Program Files/blueCFD-Core-2016/msys64/home/ofuser/ejemplos/cavity/cavity/system/system/controlDict at line 0.

    From function regIOobject::readStream()
    in file db/regIOobject/regIOobjectRead.C at line 72.

FOAM exiting
 I will appreciate any help
Hugo

**Comment by wyldckat** [comment]
Greetings Hugo,

The problem is that you executed `blockMesh` within the system folder and not within the `cavity` folder. Notice that it is complaining that it cannot find the file `controlDict` at `cavity/system/system`.

If you were to run:
```
cd ..
```
It would switch you back to the parent folder, namely `cavity`.
Best regards,
Bruno

**Comment by HugoSiles** [comment]
Hello Bruno,


you are right, I didn't realize I had to run bolckMesh from the cavity dir. Now there is no problem after running from the cavity dir.


Thanks a lot,


Hugo

________________________________
