### ISSUE TITLE
The "stochasticDispersionRAS" cannot work in simpleReactingParcelFoam

### ISSUE THREAD

**Issue by dzw05** [blueCFD/Core#42]
I tried to recompile the  "simpleReactingParcelFoam" using wmake, in fact I didnot change any source code.  When i simulate the cases under tutorials,  it output that " --> FOAM FATAL ERROR: Unknown dispersion model type stochasticDispersionRAS  Valid dispersion model types are:1(none)".

**Comment by wyldckat** [comment]
Sorry, I haven't had time yet to consolidate a User Guide for blueCFD-Core. Although there is already a wiki page that explains how to handle custom code with blueCFD-Core: https://github.com/blueCFD/Core/wiki/Loose-notes-on-building-custom-code

With blueCFD-Core, when building an OpenFOAM-based application, it's necessary to use the following commands:
```
wmake
wmakeVerifyExeDependencies ./
wmake
```

However, there is a bug in the script `wmakeVerifyExeDependencies` that was released with blueCFD-Core 2016-1, for which the fix is described here: https://github.com/blueCFD/Core/wiki/Loose-notes-on-building-custom-code#bug-fix-for-wmakeverifyexedependencies-in-bluecfd-core-2016-1

Please let us know if this solves the problem.

**Comment by dzw05** [comment]
@wyldckat ,Thanks a lot. It seems this solves the problem!

**Comment by wyldckat** [comment]
Many thanks for the feedback! I'm closing this issue as solved.
