### ISSUE TITLE
How to build swak4Foam

### ISSUE THREAD

**Issue by haibianshifeng** [blueCFD/Core#80]
Hi 

I installed the blueCFD-2017 in my Windows 7.

How to build swak4Foam using blueCFD-2017？

**Comment by wyldckat** [comment]
Many thanks for asking about swak4Foam here!

Right now, it's not yet possible to easily compile swak4Foam with blueCFD-Core 2016 and 2017.

However, given that someone has finally opened an issue for this, I will look into it as soon as possible. I did start work on it last year for blueCFD-Core 2016, but due to a few bugs in 2016-1, I had to postpone this task. But since 2016-2 and 2017-1 have been launched and the compilation bug has been fixed, it should be easier to do this sooner than later.

**Comment by wyldckat** [comment]
It's finally done! We have ported swak4Foam to blueCFD-Core 2016 and 2017!

Step-by-step installation instructions are now available here: https://github.com/blueCFD/Core/wiki/Building-swak4Foam-with-blueCFD-Core

Please keep in mind that our port of swak4Foam - source code available here: https://github.com/blueCFD/swak4Foam-dev - must be used in order to properly compile with blueCFD-Core, due to several changes that were done when porting OpenFOAM to Windows.

I'll close this report (feature request) for now. Please re-open this issue or create a new report if you have any problems building swak4Foam when following the installation instructions we have provided on the aforementioned wiki page: https://github.com/blueCFD/Core/wiki/Building-swak4Foam-with-blueCFD-Core
