### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by haibianshifeng** [blueCFD/Core#82]
My system is windows server 2008 r2. I installed the blueCFD-2017-1.

The error appears.
![2 jhf ad clqf d1 fx9](https://user-images.githubusercontent.com/19257474/34639603-bd29993a-f31d-11e7-9f44-a8df2716c3a7.png)

**Comment by wyldckat** [comment]
According to the error message, there is already another MS-MPI version installed on that machine. You can ignore the error message for now and proceed with the installation of blueCFD-Core.

After blueCFD-Core 2017-1 is installed, please start a blueCFD-Core terminal and run the following commands:

```
where mpiexec.exe
where msmpi.dll
```

This is so that we can start figuring out which versions of MS-MPI are already installed in that machine.

If you don't want to have to spend any more time figuring out which MS-MPI versions are already installed on that machine, then follow the instructions given here: http://bluecfd.github.io/Core/FAQ/mpirun-no-longer-works-in-bluecfd-core-23-1-after-installing-bluecfd-core-2016-1/#solution-1---simply-copy-the-dll-file - namely in section "Solution 1 - Simply copy the DLL file". They should work for blueCFD-Core 2017-1 as well.

**Comment by wyldckat** [comment]
Since there is no additional feedback on this issue, I'm going to close it. Please re-open if you have any news on this.
